version: 2
jobs:
  build:
    # branches:
    #   only:
    #     - master
    docker:
      - image: ellipsis/circleci_www:beta
        environment:
          AWS_REGION: us-east-1

    working_directory: ~/www
    steps:
      - checkout
      - restore_cache:
          key: package-lock-json-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: package-lock-json-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules/"
      - run:
          name: Compile site
          command: |
            npm run build && npm run export
      - run:
          name: "Deploy on staging: www.el.tc, el.tc. nocache.www.el.tc"
          command: |
            mkdir ~/.aws
            echo -e "[el-wwwstag-deployer]\naws_access_key_id = ${WWWSTAG_AWS_ACCESS_KEY}\naws_secret_access_key = ${WWWSTAG_AWS_SECRET_KEY}\nregion = us-east-1" >> ~/.aws/credentials
            aws s3 sync ./dist s3://www.el.tc/ --acl=public-read --profile=el-wwwstag-deployer
      - run:
          name: "Maybe deploy on prod"
          command: |
            if [ "${CIRCLE_BRANCH}" == "prod" ]
            then
              echo -e "[el-wwwprod-deployer]\naws_access_key_id = ${WWWPROD_AWS_ACCESS_KEY}\naws_secret_access_key = ${WWWPROD_AWS_SECRET_KEY}\nregion = us-east-1" >> ~/.aws/credentials
              aws s3 sync ./dist s3://www.ellipsis.ai/ --acl=public-read --profile=el-wwwprod-deployer
            fi
